NUMPY ARRAY OPERATION

In [2]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
print("Basic Slicing",arr[2:7])
print("With Step", arr[1:8:2]) # printing next 2 elements
print("Negative Writing",arr[-3]) # Negative indexing

Basic Slicing [3 4]
With Step [2 4]
Negative Writing 2


In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific Element",arr_2d[1,2])
print("Entire row:",arr_2d[1])
print("Entire row:",arr_2d[:,1]) #column target


Specific Element 6
Entire row: [4 5 6]
Entire row: [2 5 8]


SORTING


In [10]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("Sorted Array:",np.sort(unsorted))


arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array by column:",np.sort(arr_2d_unsorted,axis=0))
print("Sorted 2D array by row:",np.sort(arr_2d_unsorted,axis=1))



Sorted Array: [1 1 2 3 4 5 6 9]
Sorted 2D array by column: [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row: [[1 3]
 [1 2]
 [2 3]]


FILTER


In [4]:
import numpy as np
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0] # printing even numbers
print("Even Numbers:",even_number)

Even Numbers: [ 2  4  6  8 10]


FILTER WITH MASK

In [ ]:
mask = numbers > 5
print("Numbers greater than 5:",numbers[mask])

Numbers greater than 5  [ 6  7  8  9 10]


#FANCY INDEXING vs np.where()

In [9]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP Where",numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP Where [ 6  7  8  9 10]


In [15]:
condition_array = np.where(numbers > 5 , "true","false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


ADDING AND REMOVING DATA

In [16]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = arr1 + arr2
print(combined)

[5 7 9]


ARRAY COMPATIBILTY


In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])

print("Compatibility shapes :",a.shape == b.shape)

Compatibility shapes : False


In [ ]:
original = np.array([[1,2],[4,5]])

new_row = np.array([[5,6]])
with_new_row = np.vstack((original,new_row)) #vstack always adds the row
print(original)
print("New row: ",with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("New Col:",with_new_col)

[[1 2]
 [4 5]]
New row:  [[1 2]
 [4 5]
 [5 6]]
New Col: [[1 2 7]
 [4 5 8]]


In [22]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print(deleted)

[1 2 4 5]
