##Numpy array and basics
learn about numpy array and basics


In [ ]:
#PHASE-1

import numpy as np

In [ ]:
import numpy as np
arr_1d = np.array([1,2,3,4,5])
print("1D Array",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D Array",arr_2d)




1D Array [1 2 3 4 5]
2D Array [[1 2 3]
 [4 5 6]]


In [6]:
#List vs numpy array

py_list =[1,2,3]
print("Python list multiplication",py_list * 2)

np_array = np.array([1,2,3])
print("Python array multiplication",np_array *2)

Python list multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 6]


In [7]:
import time
start = time.time()
py_list = [i * 2 for i in range(1000000)]
print("\n List operation time: ",time.time() - start)# how to multiply classic list variables

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time : ",time.time() - start)






 List operation time:  0.1127018928527832

 Numpy operation time :  0.009221076965332031


In [ ]:
### creating array from scratch
import numpy as np
zeros = np.zeros((3,4))
print("zeros array: \n",zeros)

ones = np.ones((2,3))
print("ones array: \n",ones)


full = np.full((2,2),7)
print("full array : \n",full)  #Full array completely filled with 7 


random = np.random.random((2,3))
print("random array:\n ",random)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array : 
 [[7 7]
 [7 7]]
random array:
  [[0.71634891 0.18986355 0.2873105 ]
 [0.82112413 0.43259477 0.26923011]]


In [8]:
import numpy as np
vector =np.array([1,2,3])
print("Vector: ",vector)

matrix = np.array([[1,2,3],
                  [4,5,6]])
print("Matrix: ",matrix)
tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor : ",tensor)


Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor :  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [1]:
#Array properties
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print("Shape:",arr.shape)
print("Dimensions:",arr.ndim)
print("Size:",arr.size)
print("Data Type:",arr.dtype)


Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int64


In [2]:
###Array Reshaping
import numpy as np
arr = np.arange(12)
print("Original array",arr)

reshaped = arr.reshape((3,4))
print("Reshaped array",reshaped)

#flattend returns copy array
flattened = reshaped.flatten()
print("Flatten array",flattened)

#ravel returns original array
raveled = reshaped.ravel()
print("Raveled array",raveled)

#Transpose 
transpose = reshaped.T
print("Transponsed array",transpose)

Original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatten array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transponsed array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
